version: "3.8"

services:
  wifi-alert:
    build: .
    container_name: wifi-alert
    ports:
      - "3000:3000"
    environment:
      BOT_TOKEN: "YOUR_BOT_TOKEN"
      CHAT_ID: "YOUR_CHAT_ID"
    restart: unless-stopped
