version: "3.8"

services:
  omada-portal:
    build: .
    container_name: omada-telegram-portal
    ports:
      - "8080:80"
    environment:
      BOT_TOKEN: "8414483455:AAGs6rmmLdkx-uFCkpx3-9AEpFXEDXxEeXI"
      CHAT_ID: "5863793961"
    restart: unless-stopped
